version: '3.9'
services:
  palworld:
    restart: always
    container_name: palworld
    image: modded-palworld-docker-server
    env_file:
      - ./.env
    networks:
      - default
    ports:
      - "8211:8211/udp"
      - "25575:25575/tcp"
