version: '3.9'
services:
  palworld:
    restart: always
    container_name: palworld
    image: modded-palworld-docker-server
    env_file:
      - ./.env
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - PORT=${PORT}
      - PLAYERS=${PLAYERS}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
      - NO_MULTITHREADING=${NO_MULTITHREADING}
    networks:
      - default
    ports:
      - "8211:8211/udp"
      - "25575:25575/tcp"
